var jsonData = [
	{
		"title":"La storia del mio interrail",
		"content":"<p>Dicembre del 2015: leggo di un concorso fotografico organizzato da Eurodesk, un ente europeo che si occupa di creare opportunità per i giovani cittadini europei. Il concorso era ad entrata gratuita, si poteva caricare una sola immagine. Le 10 migliori foto (tramite votazione social) venivano sottoposte ad un giudizione di una giuria, che decreteva i vari vincitori (in totale 4 vincitori).<br/>In palio c'erano 4 biglietti Interrail Global Pass (all'epoca nella formula 5 in 10). Sorprendentemente la mia foto era tra le quattro vincitrici. Il premio non l'ho riscattato subito, dato che per farlo andava comunicato la data precisa di partenza.<br/>Comunicai la data solo a Maggio 2016, ma la formula 5 in 10 non era più disponibile per cui ricevetti la formula 10 (viaggi) in 30 (giorni). La foto è la seguente: #link500px# (niente di speciale a dir la verità, non essendo un fotografo professionista!).</p>"
	},
	{
		"title":"Fun-fact: il gatto diabolico e la ragazza skater",
		"content": "<p>La ragazza che mi ospitava (polacca) era molto gentile e cordiale. Lavorava ad un bar in centro e come mezzo di trasporto aveva scelto di utilizzare la longboard. <small>Il mio era amore a prima a vista</small>.<br/>Condivideva il suo terratetto su AirBnb, e aveva allestito il divano letto per me. Nell'annuncio si leggeva di un gatto, tranquillo e ben propenso a fare amiciza.<br/>Be', a leggere le recensioni nessuno si era mai lamentato del gatto ma, evidentemente, io non gli piacevo per niente. Appena arrivato voleva uccidermi.<br/>Inutile i tentativi di fare amicizia, si rintanava in cima ad un armadio per osservarmi. Il culmine della nostra, breve ma intensa, amicizia si verifica di notte (intorno alle 4): stanco della prima giornata di viaggio, dopo mangiato ed una breve camminata per il centro decido di rincasare e riposare. Il gatto era sempre sull'armadio e deve essere rimasto lì fino a che non ha deciso di saltarmi addosso (in stile \"frog splash\") per finirmi.<br/>Per mia fortuna, Sara (la sua padrona), mi salva dalle sue grinfie malefiche, portandoselo con sè nel letto.<br/>Non proprio amore a prima vista con il gatto (da parte sua verso di me!)</p>"
	},
	{
		"title":"Fun-fact: non sono un terrorista!",
		"content": "<p>La situazione in Europa era (ed è) di emergenza terrorismo. Soprattutto a Monaco, dove si era verificato da 2 settimane l'attentato al centro commerciale.<br/>Nel mio viaggio da Innsbruck a Monaco, il mio viso era più brutto e poco raccomandabile del solito: la notte e la stanchezza del viaggio del giorno precedente si faceva sentire.<br/>Decido quindi di godermi il viaggio su una carrozza deserta (solo altre 2 o 3 persone) ascoltando un po' di musica e godendomi il panorama delle Alpi.<br/>Una volta passato il confine tra Austria e Germania, alla fermata successiva sale la polizia per un controllo di dogana. Gli agenti passano tutta la carrozza deserta per poi fermarsi da me.<br/>Alzo lo sguardo. Il sangue mi si gelò e pensai: \"No, dai.. son partito ora. Cosa vogliono?\".<br/>Erano 3 agenti, di cui uno iniziò a dirmi qualcosa in tedesco. Purtroppo non sono così bravo con le lingue, per cui presumo solo che volessero vedere i documenti.<br/>Metto lentamente la mano nella tasca per prendere il portafogli e mostro i documenti (la carta d'identità).<br/>L'ufficiale tedesco era allibito. La carta d'identità è ovviamente in italiano, per cui la guarda, la gira, la fa vedere agli altri due ufficiali e dopo circa un minuto, ritorno a respirare con un \"Danke\" sospirato dall'ufficiale.<br/>Probabilmente era solo un controllo di routine, o forse mi hanno chiesto i documenti per lo stato in cui ero e per l'enorme zaino che mi portavo dietro. Non saprei, ma credevo che mi volessero far scendere dal treno per farmi qualche controllo in dogana</p>"
	},
	{
		"title":"Surfisti? A Monaco si può!",
		"content": "<p>Già, proprio così. Nel centro di Monaco c'erano davvero dei ragazzi che facevano surf! Non mi sono inventato niente!<br/>Nel parco dello 'Haus d.Kunst', all'interno di un canale, dei ragazzi si stavano sfidando su chi calvaca l'onda per più tempo! Quale onda? Quella provocata dall'acqua su diversi dossi del terreno! La corrente era molto forte, di fatto molti venivano trascinati via ma c'era un ragazzino ed una ragazza che erano dei mostri sacri! Sono subito diventati gli idoli della folla circostante.</p>"
	},
	{
		"title":"Design Concept BMW",
		"content": "<iframe width='100%' height='350px' style='border: none' src='https://www.youtube.com/embed/GjfN_exTiEI'></iframe>"
	},
	{
		"title":"Cena messicana e Narghilè con i ragazzi di Vienna!",
		"content": "<p>La mia permanenza a Vienna l'ho passata all'interno di un appartamento AirBnb, condiviso con altri ragazzi viennesi (universitari).<br/>La prima sera, caratterizzata dal diluvio universale, l'abbiamo passata raccontandoci le nostre vite davanti ad una cena messicana!<br/>I ragazzi erano fenomenali, è stata davvero una bella sera! La successiva non ci siamo trovati per un niente in un locale dove mi ero fermato per bere qualcosa, mentre l'ultima sera l'ho passata in compagnia di Zabi, che ha la mia stessa passione per l'informatica. Zabi è di origine arabe, e con alcuni suoi amici mi ha invitato ad un bar dove di solito vanno per ritrovarsi e fumare il Narghilè.<br/>Non avevo mai provato e mai mi era passato di testa l'idea di provare, ma in quei pochi giorni Zabi aveva già guadagnato la mia stima per cui è stato semplice per lui convincermi!<br/>Dopo un kebab, passammo la sera in quel locale, in compagnia degli amici di Zabi a parlare del più e del meno e di come io fossi ripartito già il giorno dopo, verso una nuova destinazione.<br/>E' incredibile come si possano creare legami così forti in così poco tempo. Sarà perché io e Zabi eravamo simili, sia per passioni sia per esperienze passate, ma il clima che si era creato era davvero unico e quasi impossibile da replicare!</p>"
	},
	{
		"title":"A praga c'erano: un italiano, un pilota, due olandesi, 1 australiano e... un ninja!",
		"content": "<p>Sembra una barzelletta ma è andata davvero così! Ci siamo conosciuti in ostello ed abbiamo passato i 3 giorni insieme, a girovagare per Praga!<br/>In una sola stanza c'erano 5 nazioni diverse.. in pratica potevamo fare un G5! E, parliamoci chiaro.. quante probabilità c'erano di trovare un pilota di Boing 747, in un ostello, a Praga? Dai.. è chiaro che dovevano essere coincidenze che auspicavano 3 bellissimi giorni! Qui di seguito una foto insieme: <br/><center><img src='/img/praha.jpg' width='300' /></center></p>"
	},
	{
		"title":"Parigi, emozioni a non finire",
		"content": "<p>Il primo giorno non potevo che spararmi Arco di Trionfo e Torre Eiffel al tramonto... una giornata quasi perfetta. L'unica eccezione è quella di non aver potuto condividere tutto ciò che ho provato con una persona accanto a me (può essere solo che un buon motivo per ritornare).<br/>Non so come possano dire che Parigi non sia una bella città o che non comunica niente... davvero, non riesco. Sfido chiunque a salire sulla Torre Eiffel, godersi il tramonto (già goderselo non significa fotografarlo) e restare ammiliato dallo spettacolo che si trova a 360gradi.<br/><br/>L'architettura di Parigi è pura arte, poesia fatta strada e quartieri. Tutto sembra essere nel punto giusto, con la luce giusta... ad aspettare solo che il tuo sguardo si posi su quel dettaglio nel momento più opportuno per far risaltare il tutto.<br/>No, non sono pazzo, credo davvero sia così! Non c'è altra spiegazione! Non mi ero mai emozionato così tanto e la cosa che più mi addolora è, appunto, non averla potuta condividere sul momento con una persona vicina a me, per dirle solo: 'Lo vedi anche tu questo spettacolo?!'</p>"
	},
	{
		"title":"Piano Versailles: come eludere le guardie, organizzare un incontro su couchsurfing e godersi lo spettacolo serale",
		"content": "<p>L'esercito francese non può niente contro di me!<br/>Nonostante la reggia di Versailles chiudesse alle 18, sono comunque riuscito ad introdurmi all'interno per godermi ancora il giardino esterno. Già, perché purtroppo avevo deciso prima di fare un giro all'interno della villa, non facendo caso però all'orario di chiusura generale! Perciò, dopo essere uscito, sono riuscito a rientrare da un entrata secondaria: solo dopo una mezz'oretta una pattuglia dell'esercito mi ferma per accompagnarmi all'uscita. Ovviamente io stavo cercando il bagno.. in mezzo ad un giardino... il giardino di Versailles.<br/>Aldilà di questo, decido comunque di restare per lo spettacolo serale (di Agosto, ogni sabato sera, organizzano uno spettacolo pirotecnico all'interno del giardino).<br/>Tramite il Couchsurfing conosco Valentina, una ragazza argentina in vacanza in Europa!<br/>Passiamo quindi una splendida sera in mezzo alla natura ed alle fontane del più bel giardino di Francia!</p>"
	},
	{
		"title":"Pranzo al Louvre e cibo da 'giornata lavorativa' al Moulin Rouge",
		"content": "<p>E' vero che per quanto riguarda la cucina noi italiani siamo dei fenomeni, ma mi ero promesso di provare almeno un pasto tipico della città che visitavo.<br/>Oltre le baguette, che mi hanno accompagnato per molti pranzi, tra cui anche al Museo del Louvre mi son concesso un pranzo degno di nota nel quartiere del Moulin Rogue.<br/>Cercando su tripadvisor sono riuscito a trovare una specie di 'osteria' dove spesso vanno, in pausa pranzo, i lavoratori francesi delle vicinanze. L'osteria è davvero piccola, il proprietario era un vecchio signore e sua figlia faceva da cameriera. L'ambiente era povero di inglese, ma nonostante questo si respirava un bellissimo clima di ospitalità ed umiltà. Era il posto giusto!<br/>Il menù era molto semplice: un primo piatto ed un secondo, con il caffè a seguito. Tutto carammelato, con formaggio e burro...ed ovviamente tutto squisito!</p>"
	},
	{
		"title":"Paella, Pub Crawl, Barcelonita, Transfomers e Silicon Valley",
		"content": "<p>Be', ok, Barcellona è conosciuta per la sua movida. Ero sì stanco, ma ero più stanco del fatto che piovesse tutto il giorno. L'ostello dove dormivo era molto rock e i ragazzi che ci abitavano organizzavano sempre qualcosa la sera, sia dentro che fuori.<br/>Abbiamo cenato tutti insieme, giocato ad uno strano gioco di carte (credo inglese) e fatto baldoria nei locali della Barcelonita. La sera più assurda fu la prima. Restai sveglio per 27 ore di fila, perché arrivavo da Parigi con un viaggio di oltre 6h di treno, e tornammo all'ostello dopo l'alba.<br/>Sembra strano, ma legai subito con due ragazzi statunitensi e australiani. I primi parlavano anche un po' di italiano, ed erano anche loro dei web dev, mentre i secondi era già diffile capirli in inglese che l'italiano.. per favore lascialo stare!<br/><br/>Dopo tutte quelle ore sveglio ad un certo punto intravidi delle sagome di due Transformer avvicinarsi a me.. pensavo di essere fuso ed invece c'erano davvero! Allucinante, credo sia stata una delle giornate più pazze che abbia vissuto e non ci sono parole per descriverla!</p>"
	},
	{
		"title":"The end",
		"content": "<p>Marsiglia è stata l'ultima tappa, quasi forzata, per tornare in patria! La stanchezza si è fatta sentire tutta di colpo, ma per fortuna la giornata era ottima per un po' di mare. Sguazzando per il vicino mare di Marsiglia, riesco a godermi un tramonto spettacolare sul suo golfo.<br>Era il tipico tramonto da ammirare nella sua interezza, per quei 20minuti. Immobile, guardando l'orizzonte. Il panorama era unico, tante piccole isole che lasciavano spazio al sole via via che si spegneva nel mare.<br/>La scena clou è stata quando, all'improvviso, una grossa nave da crociera al largo di Marsiglia, si sovrappone con la sua sagoma a quella del sole creando così una \"eclissi parziale\"! Unico.<br><br/>Lì, ho finalmente capito che il mio viaggio stava finendo.</p>"
	},
	{
		"title":"Chi è Ully? La ragazza perfetta",
		"content": "<p>Ully mully è la tipica ragazza semplice con la quale puoi scherzare, confidarti e affrontare avventure che vanno dalla quotidianetà all'estremo con una facilità disarmante. Tutto viene spontaneo con lei... non puoi fare altrimenti!<br/>I suoi occhi, da vera tedesca, sono ipnotici: riesce a comunicarti qualsiasi cosa tramite lo sguardo. Non so quante volte ho capito, da quello sguardo, cosa esattamente volesse dirmi... per non contare tutte quelle volte che mi ci sono perso, in quel bellissimo blu.<br/><br/>Ully è tra l'altro una persona con un dei caratteri più forti che conosca! Sono incredibili le esperienze che ha passato e che sta passando, sia in Germania sia ora in Italia. Non mento quando dico che è la ragazza perfetta: \"The one\" o la \"The chosen one\". Starei ore a parlare con lei, gli argomenti tendono a più infinito. Per non parlare dei suoi brownies o delle scarpinate che potrebbe fare sulle montagne e nei boschi!<br/><br/>E' davvero unica ed io la amo (se non si era capito).</p>"
	},
	{
		"title":"Relax, Parco e.. bici!",
		"content": "<p>Berlino è troppo grande e non ha un vero e proprio centro...come visitarla tutta? Soluzione: bici!<br>Città immensa, piena di piste ciclabile e con mia sorpresa.. anche di parchi! Non è da me fermarmi nei parchi, per rilassarmi, dormire un pochino e godersi il tempo che scorre. Berlino, immensamente unica!</p>"
	},
	{
		"title":"La prima volta non si scorda mai",
		"content": "<p>Amsterdam, si sa, è la città di Lucignolo. E' possibile sperimentare qualsiasi cosa in un ambiente sicuro e controllato, senza avere pensier strani o esser considerato illegale.<br>Si conferma una delle città più belle d'Europa e del Mondo, e si capiscano i vari perché solo quando si passano alcuni giorni.<br/><br/>L'unico dispiacere è non poterla vivere per più tempo, come fosse vita quotidiana. Sarebbe una bella sfida!</p>"
	},
	{
		"title":"Notre Dame e la Senna: un due meraviglioso",
		"content": "<p>Non c'è altro da aggiungere.</p>"
	},
	{
		"title":"RUN! Motorino, mare e... Marta!",
		"content": "<p>Nuvoloso e stanchezza non è la miglior situazione per affrontare la giornata da solo... ci voleva un'idea... ok, ci sono: Noleggio un motorino e mi faccio la panoramica sulla costa, verso sud!<br/><br/>Piccola premessa: io ho la patente per il 125manuale, ma non ho mai guidato (se non per l'esame) un motorino o moto, per cui era la prima volta effettiva che usavo un motorino.. ed è stato epico.<br/>Sulla panoramica non c'erano autovelox, per cui mi sono goduto il panorama e la strada che costeggiava il mare! Il panorama era caratterizzato da queste scogliere a strapiombo che si affacciavano sul mare. La strada era bella larga e tortuosa, intermezzata da alcune brevi gallerie. L'obbiettivo della giornata era trovare bel tempo e una caletta dove poter farsi il bagno, in un'acqua degna di tale nome.<br/><br/>Il sole non sono riuscito a trovarlo, ma la caletta si, e come!<br/>Quel piccolo viaggio all'interno del viaggio mi ha eliminato qualsiasi limite, paura o pensiero negativo che potessi avere. E' stata una liberazione, mi sentivo di vivere il momento.. di stare rock!<br/><br/>Tutto questo stare bene l'ho condiviso con Marta, un'amica che mi conosce più per le parti negative e \"depresse\" di me. Stavo talmente bene che sembravo un'altra persona al telefono con lei! Mi ha fatto piacere \"raccontarle\" la vera versione di Miki, quella sana, felice con la quale puoi scherzare, confidarti e divertirti.<br/><br/>Si, quella spiaggetta e quel viaggio nel viaggio è stato super... mi ha dato altre idee ma, soprattutto, mi ha fatto scoprire ancora una volta il vero me.</p>"
	}
];